package com.billcom.mobileportability;

import com.billcom.mobileportability.Data;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CancelPortabilityOrder extends Data
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("NPId")
	private java.lang.String nPId;

	@org.kie.api.definition.type.Label("NPRequestId")
	private java.lang.String nPRequestId;

	@org.kie.api.definition.type.Label("MessageCode")
	private java.lang.String messageCode;

	@org.kie.api.definition.type.Label("ProcessType")
	private java.lang.String processType;

	public CancelPortabilityOrder() {
	}

	public java.lang.String getnPId() {
		return this.nPId;
	}

	public void setnPId(java.lang.String nPId) {
		this.nPId = nPId;
	}

	public java.lang.String getnPRequestId() {
		return this.nPRequestId;
	}

	public void setnPRequestId(java.lang.String nPRequestId) {
		this.nPRequestId = nPRequestId;
	}

	public java.lang.String getmessageCode() {
		return this.messageCode;
	}

	public void setmessageCode(java.lang.String messageCode) {
		this.messageCode = messageCode;
	}

	public java.lang.String getProcessType() {
		return this.processType;
	}

	public void setProcessType(java.lang.String processType) {
		this.processType = processType;
	}
	public java.lang.String toString() {
		return "CancelPortabilityOrder [ nPId=" + this.nPId + ", nPRequestId="
				+ this.nPRequestId + ", messageCode=" + this.messageCode
				+ ", processType=" + this.processType + "]";
	}

	public CancelPortabilityOrder(java.lang.String nPId,
			java.lang.String nPRequestId, java.lang.String messageCode,
			java.lang.String processType) {
		this.nPId = nPId;
		this.nPRequestId = nPRequestId;
		this.messageCode = messageCode;
		this.processType = processType;
	}

}