package com.billcom.mobileportability;

import com.billcom.mobileportability.Model;
import com.billcom.mobileportability.Data;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ChangeDN extends Data implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("coIdPub")
	private java.lang.String coIdPub;

	@org.kie.api.definition.type.Label("dirNum")
	private java.lang.String dirNum;

	@org.kie.api.definition.type.Label("service")
	private java.lang.String service;

	@org.kie.api.definition.type.Label("DNTarget")
	private java.lang.String dnTarget;

	@org.kie.api.definition.type.Label("Retention")
	private java.lang.String retention;

	public ChangeDN() {
	}

	public java.lang.String getCoIdPub() {
		return this.coIdPub;
	}

	public void setCoIdPub(java.lang.String coIdPub) {
		this.coIdPub = coIdPub;
	}

	public java.lang.String getDirNum() {
		return this.dirNum;
	}

	public void setDirNum(java.lang.String dirNum) {
		this.dirNum = dirNum;
	}

	public java.lang.String getService() {
		return this.service;
	}

	public void setService(java.lang.String service) {
		this.service = service;
	}
	public String toString() {
		return "ChangeDN [coIdPub=" + this.coIdPub
				+ ", dirNum=" + this.dirNum + ", service=" + this.service
				+ ", dnTarget=" + this.dnTarget + "]";
	}
	public java.lang.String getDnTarget() {
		return this.dnTarget;
	}

	public void setDnTarget(java.lang.String dnTarget) {
		this.dnTarget = dnTarget;
	}

	public java.lang.String getRetention() {
		return this.retention;
	}

	public void setRetention(java.lang.String retention) {
		this.retention = retention;
	}

	public ChangeDN(java.lang.String coIdPub, java.lang.String dirNum,
			java.lang.String service, java.lang.String dnTarget,
			java.lang.String retention) {
		this.coIdPub = coIdPub;
		this.dirNum = dirNum;
		this.service = service;
		this.dnTarget = dnTarget;
		this.retention = retention;
	}

}