package com.billcom.mobileportability;

import com.billcom.mobileportability.Data;

/**
 * This class was automatically generated by the data modeler tool
 */

@javax.persistence.Entity
public class ImportExternalResource extends Data
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("dnTarget")
	private java.lang.String dnTarget;

	@org.kie.api.definition.type.Label("csIdPub")
	private java.lang.String csIdPub;

	@org.kie.api.definition.type.Label("coIdPub")
	private java.lang.String coIdPub;

	@org.kie.api.definition.type.Label("operatorCode")
	private java.lang.String operatorCode;

	public ImportExternalResource() {
	}

	public java.lang.String getDnTarget() {
		return this.dnTarget;
	}

	public void setDnTarget(java.lang.String dnTarget) {
		this.dnTarget = dnTarget;
	}

	public java.lang.String getCsIdPub() {
		return this.csIdPub;
	}

	public void setCsIdPub(java.lang.String csIdPub) {
		this.csIdPub = csIdPub;
	}

	public java.lang.String getCoIdPub() {
		return this.coIdPub;
	}

	public void setCoIdPub(java.lang.String coIdPub) {
		this.coIdPub = coIdPub;
	}

	public java.lang.String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(java.lang.String operatorCode) {
		this.operatorCode = operatorCode;
	}
	public java.lang.String toString() {
		return "ImportExternalResource [ dnTarget=" + this.dnTarget
				+ ", csIdPub=" + this.csIdPub + ", coIdPub=" + this.coIdPub
				+ ", operatorCode=" + this.operatorCode + "]";
	}
	public ImportExternalResource(java.lang.String dnTarget,
			java.lang.String csIdPub, java.lang.String coIdPub,
			java.lang.String operatorCode) {
		this.dnTarget = dnTarget;
		this.csIdPub = csIdPub;
		this.coIdPub = coIdPub;
		this.operatorCode = operatorCode;
	}

}