package com.billcom.mobileportability;

/**
 * This class was automatically generated by the data modeler tool
 */

@javax.persistence.Entity
public class Model implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label("ProcessId")
	private Long processId;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("Data")
	private com.billcom.mobileportability.Data data;

	@org.kie.api.definition.type.Label("WebService")
	private java.lang.String webService;

	public Model() {
	}

	public void setModel(com.billcom.mobileportability.Data data) {
		this.data = data;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Long getProcessId() {
		return this.processId;
	}

	public void setProcessId(java.lang.Long processId) {
		this.processId = processId;
	}

	public com.billcom.mobileportability.Data getData() {
		return this.data;
	}

	public void setData(com.billcom.mobileportability.Data data) {
		this.data = data;
	}

	public java.lang.String getWebService() {
		return this.webService;
	}

	public void setWebService(java.lang.String webservice) {
		this.webService = webservice;
	}
	@Override
	public java.lang.String toString() {
		return "Model [data=" + this.data + ", webService=" + this.webService + ", status=" + this.status + ", processId=" + this.processId
				+ "]";
	}

	public Model(java.lang.String status, java.lang.Long processId,
			com.billcom.mobileportability.Data data, java.lang.String webService) {
		this.status = status;
		this.processId = processId;
		this.data = data;
		this.webService = webService;
	}

}