package com.billcom.mobileportability;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Np implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("PartialPorting")
	private java.lang.Boolean partialPorting;

	public Np() {
	}

	public java.lang.Boolean getPartialPorting() {
		return this.partialPorting;
	}

	public void setPartialPorting(java.lang.Boolean partialPorting) {
		this.partialPorting = partialPorting;
	}
	public java.lang.String toString() {
		return "Np [ partialPorting=" + this.partialPorting
				+ "]";
	}

	public Np(java.lang.Boolean partialPorting) {
		this.partialPorting = partialPorting;
	}

}