package com.billcom.mobileportability;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Nr implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("RIO")
	private java.lang.String RIO;

	@org.kie.api.definition.type.Label("Number")
	private java.lang.String number;

	public Nr() {
	}

	public java.lang.String getRIO() {
		return this.RIO;
	}

	public void setRIO(java.lang.String RIO) {
		this.RIO = RIO;
	}

	public java.lang.String getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.String number) {
		this.number = number;
	}
	public java.lang.String toString() {
		return "Nr [RIO=" + this.RIO + ", Number=" + this.number + "]";
	}
	public Nr(java.lang.String RIO, java.lang.String number) {
		this.RIO = RIO;
		this.number = number;
	}

}