package com.billcom.mobileportability;

import com.billcom.mobileportability.Data;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class SmsNotification extends Data implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("To")
	private String to;

	@org.kie.api.definition.type.Label("Msg")
	private java.lang.String msg;

	@org.kie.api.definition.type.Label(value = "DueDate")
	private java.lang.String dueDate;

	public SmsNotification() {
	}

	public java.lang.String getMsg() {
		return this.msg;
	}

	public void setMsg(java.lang.String msg) {
		this.msg = msg;
	}
	public java.lang.String toString() {
		return "SmsNotification [ to=" + this.to + ", msg=" + this.msg + ", dueDate="+this.dueDate +"]";
	}
	public java.lang.String getTo() {
		return this.to;
	}

	public void setTo(java.lang.String to) {
		this.to = to;
	}

	public java.lang.String getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(java.lang.String dueDate) {
		this.dueDate = dueDate;
	}

	public SmsNotification(java.lang.String to, java.lang.String msg,
			java.lang.String dueDate) {
		this.to = to;
		this.msg = msg;
		this.dueDate = dueDate;
	}

}