package com.billcom.mobileportability;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class UpdatePortabilityStatusResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ErrorOrigin")
	private java.lang.String errorOrigin;

	@org.kie.api.definition.type.Label("ErrorDetail")
	private java.lang.String errorDetail;

	@org.kie.api.definition.type.Label("IsSuccessful")
	private java.lang.Boolean isSuccessful;

	public UpdatePortabilityStatusResponse() {
	}

	public java.lang.String getErrorOrigin() {
		return this.errorOrigin;
	}

	public void setErrorOrigin(java.lang.String errorOrigin) {
		this.errorOrigin = errorOrigin;
	}

	public java.lang.String getErrorDetail() {
		return this.errorDetail;
	}

	public void setErrorDetail(java.lang.String errorDetail) {
		this.errorDetail = errorDetail;
	}

	public java.lang.Boolean getIsSuccessful() {
		return this.isSuccessful;
	}

	public void setIsSuccessful(java.lang.Boolean isSuccessful) {
		this.isSuccessful = isSuccessful;
	}
	public java.lang.String toString() {
		return "UpdatePortabilityStatusResponse [ errorOrigin=" + this.errorOrigin + ", errorDetail="
				+ this.errorDetail + ", isSuccessful=" + this.isSuccessful
				+ "]";
	}
	public UpdatePortabilityStatusResponse(java.lang.String errorOrigin,
			java.lang.String errorDetail, java.lang.Boolean isSuccessful) {
		this.errorOrigin = errorOrigin;
		this.errorDetail = errorDetail;
		this.isSuccessful = isSuccessful;
	}

}